version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: userdb
      JWT_SECRET: supersecret
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    volumes:
      - ./user-service:/usr/src/app
    command: npm run dev

volumes:
  pgdata:
